name       : python-txtorcon
version    : 0.20.0
release    : 2
source     :
    - https://github.com/meejah/txtorcon/archive/v0.20.0.tar.gz : 75c5880b25dcf613129351d69c1682c111a33c3243c99a0642026a7a8f9247ae
license    : MIT
component  : programming.python
summary    : A Twisted-based Python asynchronous controller library for Tor
description: |
    A Twisted-based Python asynchronous controller library for Tor
rundeps    :
    - python-geoip
    - python-twisted
setup      : |
    %python3_setup
install    : |
    %python3_install
