name       : python-txtorcon
version    : 21.1.0
release    : 6
source     :
    - https://github.com/meejah/txtorcon/archive/refs/tags/v21.1.0.tar.gz : 61ef40e110a2b52255a6033293d02647dedb63ed9311ce572571c777b2302750
license    : MIT
component  : programming.python
summary    : A Twisted-based Python asynchronous controller library for Tor
description: |
    A Twisted-based Python asynchronous controller library for Tor
builddeps  :
    - lsof # check
    - python-mock # check
    - python-pytest # check
    - python-twisted # check
    - python-zope.interface # check
rundeps    :
    - python-geoip
    - python-twisted
setup      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    3 tests failing
#    %python3_test pytest3
