name       : python-txtorcon
version    : 20.0.0
release    : 3
source     :
    - https://github.com/meejah/txtorcon/archive/v20.0.0.tar.gz : 8b5f5587ab03bb965c4d162b8ef86c6853c06041b200f2f8a2272caa4bd7cac4
license    : MIT
component  : programming.python
summary    : A Twisted-based Python asynchronous controller library for Tor
description: |
    A Twisted-based Python asynchronous controller library for Tor
rundeps    :
    - python-geoip
    - python-twisted
setup      : |
    %python3_setup
install    : |
    %python3_install
